### ISSUE TITLE
Missing LICENSE File

### ISSUE THREAD

**Issue by char0n** [phadej/trampa#1]
Hello, is it possible to incorporate the LICENSE file inside the npm package and this github repo ? Now it's missing. It's implied by MIT license that if licensed under the MIT the source code must be accompanied by full license text. If the license file is not in the npm package or a github repo a lot of people cannot use it (technically nobody).

Thank you

**Comment by phadej** [comment]
resolved in https://www.npmjs.com/package/trampa/v/1.0.1

**Comment by char0n** [comment]
Thank you very much
